# Generated by Django 3.1.4 on 2023-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_flashcard_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='current_bin',
            field=models.CharField(default='bin0', max_length=200),
        ),
    ]
