# Generated by Django 3.1.4 on 2023-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_flashcard_current_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_bin_change',
            field=models.DateTimeField(default='2000-01-01 00:00:00.000000+00:00'),
        ),
    ]
